package picklab.backend.activity.application.model

import picklab.backend.activity.domain.enums.ActivityFieldType
import picklab.backend.activity.domain.enums.ActivityType
import picklab.backend.activity.domain.enums.DomainType
import picklab.backend.activity.domain.enums.EducationCostType
import picklab.backend.activity.domain.enums.EducationFormatType
import picklab.backend.activity.domain.enums.LocationType
import picklab.backend.activity.domain.enums.OrganizerType
import picklab.backend.activity.domain.enums.ParticipantType
import picklab.backend.activity.domain.enums.RecruitmentEndType
import picklab.backend.activity.domain.enums.RecruitmentStatus
import java.time.LocalDate

sealed class ActivityCreateCommand(
    open val activityType: ActivityType,
    open val activityGroupId: Long,
    open val title: String,
    open val organizer: String?,
    open val organizerType: OrganizerType,
    open val targetAudience: ParticipantType,
    open val recruitmentStartDate: LocalDate,
    open val recruitmentEndDate: LocalDate?,
    open val recruitmentEndType: RecruitmentEndType,
    open val startDate: LocalDate,
    open val endDate: LocalDate?,
    open val status: RecruitmentStatus,
    open val duration: Int,
    open val activityHomepageUrl: String?,
    open val activityApplicationUrl: String?,
    open val activityThumbnailUrl: String?,
    open val description: String?,
    open val benefit: String,
    open val jobCategories: List<ActivityJobCategoryCommand>,
    open val uploadFiles: List<ActivityUploadFileCommand>,
)

data class ExternalActivityCreateCommand(
    override val activityGroupId: Long,
    override val title: String,
    override val organizer: String? = null,
    override val organizerType: OrganizerType,
    override val targetAudience: ParticipantType,
    override val recruitmentStartDate: LocalDate,
    override val recruitmentEndDate: LocalDate?,
    override val recruitmentEndType: RecruitmentEndType,
    override val startDate: LocalDate,
    override val endDate: LocalDate?,
    override val status: RecruitmentStatus,
    override val duration: Int,
    override val activityHomepageUrl: String?,
    override val activityApplicationUrl: String?,
    override val activityThumbnailUrl: String?,
    override val description: String?,
    override val benefit: String,
    override val jobCategories: List<ActivityJobCategoryCommand>,
    override val uploadFiles: List<ActivityUploadFileCommand>,
    val location: LocationType,
    val activityField: ActivityFieldType,
) : ActivityCreateCommand(
        activityType = ActivityType.EXTRACURRICULAR,
        activityGroupId = activityGroupId,
        title = title,
        organizer = organizer,
        organizerType = organizerType,
        targetAudience = targetAudience,
        recruitmentStartDate = recruitmentStartDate,
        recruitmentEndDate = recruitmentEndDate,
        recruitmentEndType = recruitmentEndType,
        startDate = startDate,
        endDate = endDate,
        status = status,
        duration = duration,
        activityHomepageUrl = activityHomepageUrl,
        activityApplicationUrl = activityApplicationUrl,
        activityThumbnailUrl = activityThumbnailUrl,
        description = description,
        benefit = benefit,
        jobCategories = jobCategories,
        uploadFiles = uploadFiles,
    )

data class SeminarActivityCreateCommand(
    override val activityGroupId: Long,
    override val title: String,
    override val organizer: String? = null,
    override val organizerType: OrganizerType,
    override val targetAudience: ParticipantType,
    override val recruitmentStartDate: LocalDate,
    override val recruitmentEndDate: LocalDate?,
    override val recruitmentEndType: RecruitmentEndType,
    override val startDate: LocalDate,
    override val endDate: LocalDate?,
    override val status: RecruitmentStatus,
    override val duration: Int,
    override val activityHomepageUrl: String?,
    override val activityApplicationUrl: String?,
    override val activityThumbnailUrl: String?,
    override val description: String?,
    override val benefit: String,
    override val jobCategories: List<ActivityJobCategoryCommand>,
    override val uploadFiles: List<ActivityUploadFileCommand>,
    val location: LocationType,
) : ActivityCreateCommand(
        activityType = ActivityType.SEMINAR,
        activityGroupId = activityGroupId,
        title = title,
        organizer = organizer,
        organizerType = organizerType,
        targetAudience = targetAudience,
        recruitmentStartDate = recruitmentStartDate,
        recruitmentEndDate = recruitmentEndDate,
        recruitmentEndType = recruitmentEndType,
        startDate = startDate,
        endDate = endDate,
        status = status,
        duration = duration,
        activityHomepageUrl = activityHomepageUrl,
        activityApplicationUrl = activityApplicationUrl,
        activityThumbnailUrl = activityThumbnailUrl,
        description = description,
        benefit = benefit,
        jobCategories = jobCategories,
        uploadFiles = uploadFiles,
    )

data class EducationActivityCreateCommand(
    override val activityGroupId: Long,
    override val title: String,
    override val organizer: String? = null,
    override val organizerType: OrganizerType,
    override val targetAudience: ParticipantType,
    override val recruitmentStartDate: LocalDate,
    override val recruitmentEndDate: LocalDate?,
    override val recruitmentEndType: RecruitmentEndType,
    override val startDate: LocalDate,
    override val endDate: LocalDate?,
    override val status: RecruitmentStatus,
    override val duration: Int,
    override val activityHomepageUrl: String?,
    override val activityApplicationUrl: String?,
    override val activityThumbnailUrl: String?,
    override val description: String?,
    override val benefit: String,
    override val jobCategories: List<ActivityJobCategoryCommand>,
    override val uploadFiles: List<ActivityUploadFileCommand>,
    val location: LocationType,
    val cost: Long,
    val costType: EducationCostType,
    val educationFormat: EducationFormatType,
) : ActivityCreateCommand(
        activityType = ActivityType.EDUCATION,
        activityGroupId = activityGroupId,
        title = title,
        organizer = organizer,
        organizerType = organizerType,
        targetAudience = targetAudience,
        recruitmentStartDate = recruitmentStartDate,
        recruitmentEndDate = recruitmentEndDate,
        recruitmentEndType = recruitmentEndType,
        startDate = startDate,
        endDate = endDate,
        status = status,
        duration = duration,
        activityHomepageUrl = activityHomepageUrl,
        activityApplicationUrl = activityApplicationUrl,
        activityThumbnailUrl = activityThumbnailUrl,
        description = description,
        benefit = benefit,
        jobCategories = jobCategories,
        uploadFiles = uploadFiles,
    )

data class CompetitionActivityCreateCommand(
    override val activityGroupId: Long,
    override val title: String,
    override val organizer: String? = null,
    override val organizerType: OrganizerType,
    override val targetAudience: ParticipantType,
    override val recruitmentStartDate: LocalDate,
    override val recruitmentEndDate: LocalDate?,
    override val recruitmentEndType: RecruitmentEndType,
    override val startDate: LocalDate,
    override val endDate: LocalDate?,
    override val status: RecruitmentStatus,
    override val duration: Int,
    override val activityHomepageUrl: String?,
    override val activityApplicationUrl: String?,
    override val activityThumbnailUrl: String?,
    override val description: String?,
    override val benefit: String,
    override val jobCategories: List<ActivityJobCategoryCommand>,
    override val uploadFiles: List<ActivityUploadFileCommand>,
    val domain: DomainType,
    val cost: Long,
) : ActivityCreateCommand(
        activityType = ActivityType.COMPETITION,
        activityGroupId = activityGroupId,
        title = title,
        organizer = organizer,
        organizerType = organizerType,
        targetAudience = targetAudience,
        recruitmentStartDate = recruitmentStartDate,
        recruitmentEndDate = recruitmentEndDate,
        recruitmentEndType = recruitmentEndType,
        startDate = startDate,
        endDate = endDate,
        status = status,
        duration = duration,
        activityHomepageUrl = activityHomepageUrl,
        activityApplicationUrl = activityApplicationUrl,
        activityThumbnailUrl = activityThumbnailUrl,
        description = description,
        benefit = benefit,
        jobCategories = jobCategories,
        uploadFiles = uploadFiles,
    )

data class ActivityJobCategoryCommand(
    val jobGroup: picklab.backend.job.domain.enums.JobGroup,
    val jobDetail: picklab.backend.job.domain.enums.JobDetail?,
)

data class ActivityUploadFileCommand(
    val name: String,
    val url: String,
)
