-- 대분류만 (job_detail은 NULL)
INSERT INTO job_category (job_group, job_detail)
VALUES
    ('PLANNING', NULL),
    ('DESIGN', NULL),
    ('DEVELOPMENT', NULL),
    ('MARKETING', NULL),
    ('AI', NULL);

-- 세부 분류 (job_group + job_detail)
INSERT INTO job_category (job_group, job_detail)
VALUES
-- 기획
('PLANNING', 'SERVICE_PLANNING'),
('PLANNING', 'BUSINESS_DEVELOPMENT'),
('PLANNING', 'DATA_ANALYSIS'),
('PLANNING', 'PM_PO'),

-- 디자인
('DESIGN', 'UX_DESIGN'),
('DESIGN', 'UI_DESIGN'),
('DESIGN', 'WEB_DESIGN'),
('DESIGN', 'GRAPHIC_DESIGN'),
('DESIGN', 'BRAND_DESIGN'),

-- 개발
('DEVELOPMENT', 'FRONTEND'),
('DEVELOPMENT', 'BACKEND'),
('DEVELOPMENT', 'FULLSTACK'),
('DEVELOPMENT', 'SECURITY'),
('DEVELOPMENT', 'DEVOPS'),
('DEVELOPMENT', 'IOS'),
('DEVELOPMENT', 'ANDROID'),
('DEVELOPMENT', 'BLOCKCHAIN'),
('DEVELOPMENT', 'GAME'),

-- 마케팅
('MARKETING', 'BRAND_MARKETING'),
('MARKETING', 'CONTENT_MARKETING'),
('MARKETING', 'GROWTH_MARKETING'),
('MARKETING', 'PERFORMANCE_MARKETING'),
('MARKETING', 'PR'),

-- AI
('AI', 'MACHINE_LEARNING'),
('AI', 'DEEP_LEARNING'),
('AI', 'COMPUTER_VISION'),
('AI', 'NLP'),
('AI', 'DATA_SCIENCE');
