-- 북마크 테이블
CREATE TABLE IF NOT EXISTS bookmark
(
    id          BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '북마크 ID',
    member_id   BIGINT COMMENT '회원 ID',
    activity_id BIGINT COMMENT '활동 ID',
    created_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    updated_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='북마크 테이블';